### ISSUE TITLE
Program Course isnt actually many to many

### ISSUE THREAD

**Issue by Bluerberry** [PRIME-TU-Delft/graaf-svelte-4#64]
Unless I misunderstand our prisma schema, a course can currently be associated to only one program

**Comment by BEvanGelderen** [comment]
A course should be able to belong to multiple programs, or none at all! For example: WBMT1050 is both PRIME and 3ME.

**Comment by juliavdkris** [comment]
This actually already has been implemented on https://github.com/PRIME-TU-Delft/graaf/tree/db-improve-roles-links! We might want to just merge that branch, even though auth is still a bit broken

Bram said that might cause merge conflicts or other weirdness because of moved files, but from local testing it seems like we're good. I'll make a PR for it :)

**Comment by juliavdkris** [comment]
PR: #69 (still work-in-progress, gotta run to lecture hahah)

**Comment by Bluerberry** [comment]
Nice PR nr
